import "./math.pine"
import "./core.pine"

def (this List{T}) ++ (that List{T}) -> List{T}
    <javascript>
    return $this.concat($that);
    </javascript>

def (this List{T}).(that Number) -> T 
    <javascript>
    return $this[$that]
    </javascript>

def (this List{T}).(start Number to end Number) -> T 
    <javascript>
    return $this.slice($start, $end + 1)
    </javascript>

def (this List{T}).length -> Number
    <javascript>
    return $this.length;
    </javascript>


def (this List{T}).append(that T) -> List{T}
    return this ++ [that]

def (this List{T}).prepend(that T) -> List{T}
    return [that] ++ this

def (this Number)..<(that Number) -> List{Number}
    if this == (that - 1)
        return [this]
    else
        return [this] ++ ((this + 1)..<that)

def (this List{T}).at(index Int put value T) -> List{T}
    <javascript>
    $this[$index] = $value
    return $this
    </javascript>