import "./math.pine"
import "./core.pine"

def (this List{T}) ++ (that List{T}) -> List{T}
    <javascript>
    return $this.concat($that);
    </javascript>


def (this List{T}).length -> Number
    <javascript>
    return $this.length;
    </javascript>


def (this List{T}).append(that T) -> List{T}
    return this ++ [that]


def (this List{T}).prepend(that T) -> List{T}
    return [that] ++ this

def (this List{T}).from(start Number to: end Number) -> List{T}
    <javascript>
    return $this.slice($start, $end + 1)
    </javascript>

def (this Number)..<(that Number) -> List{Number}
    if this == (that - 1)
        return [this]
    else
        return [this] ++ ((this + 1)..<that)
