def (this Number) + (that Number) -> Number
    <javascript>
    return $this + $that;
    </javascript>

def (this Number) - (that Number) -> Number
    <javascript>
    return $this - $that;
    </javascript>

def (this Number) * (that Number) -> Number
    <javascript>
    return $this * $that;
    </javascript>

def (this Number) / (that Number) -> Number
    <javascript>
    return $this / $that;
    </javascript>

def (this Number) ^ (that Number) -> Number
    <javascript>
    return Math.pow($this, $that);
    </javascript>

def (this Number) < (that Number) -> Boolean
    <javascript>
    return $this < $that;
    </javascript>

