import "./boolean"

def Nil
    #nil

def Undefined
    #undefined

def (this Any) == (that Any) -> Boolean
    <javascript>
    return $this === $that;
    </javascript>

def (this Any) =/= (that Any) -> Boolean
    <javascript>
    return $this !== $that;
    </javascript>

def (this Any) != (that Any) -> Boolean
    return this =/= that

def (this String).toInteger -> Integer
    <javascript>
    return parseInt($this);
    </javascript>

def (this Any).toString -> String
    <javascript>
    return $this.toString();
    </javascript>