def (this Any).show 
    <javascript>
    console.log($this)
    </javascript>

def async (question String).ask -> String
    <javascript>
    const readline = require('readline');

    const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
    });

    return new Promise((resolve, reject) => {
        rl.question($question, (message) => {
            resolve(message);
            rl.close();
        });
    })
    </javascript>