import "./core"

def - (this Number) -> Number
    <javascript>
    return - $this;
    </javascript>

def (this Number) + (that Number) -> Number
    <javascript>
    return $this + $that;
    </javascript>

def (this Integer) + (that Integer) -> Integer
    <javascript>
    return $this + $that;
    </javascript>

def (this Integer) - (that Integer) -> Integer
    <javascript>
    return $this - $that;
    </javascript>

def (this Number) - (that Number) -> Number
    <javascript>
    return $this - $that;
    </javascript>

def (this Number) * (that Number) -> Number
    <javascript>
    return $this * $that;
    </javascript>

def (this Number) / (that Number) -> Number
    <javascript>
    return $this / $that;
    </javascript>

def (this Number) % (that Number) -> Number
    <javascript>
    return $this % $that;
    </javascript>

def (this Number) ^ (that Number) -> Number
    <javascript>
    return Math.pow($this, $that);
    </javascript>

def (this Number) < (that Number) -> Boolean
    <javascript>
    return $this < $that;
    </javascript>

def (this Number) > (that Number) -> Boolean
    <javascript>
    return $this > $that;
    </javascript>

def (this Number) >= (that Number) -> Boolean
    return (this > that).or(this == that)

def (this Number) <= (that Number) -> Boolean
    return (this < that).or(this == that)

