import "core"

def (this String).indexOf(that String) -> Integer
    pass

def (this String).replace(old String with new String) -> String
    return this.splitBy(old).joinBy(new)

def (this String).splitBy(that String) -> String
    <javascript>
    return $this.split($that);
    </javascript>

def (this String).joinBy(that String) -> String
    <javascript>
    return $this.join($that)
    </javascript>