(*
Abbreviations:
    Decl = Declaration
    Stmt = Statement   
    Id   = Identifier
    Expr = Expression
    Lit  = Literal
    Arg  = Argument
    Op   = Operator
    Var  = Variable
    Func = Function
*)
EntryPoint = {Decl};

Decl
    = EnumDecl
    | ImportDecl
    | StructDecl
    | FuncDecl
    ;

EnumDecl
    = DEF TypeId NEWLINE INDENT {Enum} DEDENT
    ;

ImportDecl
    = IMPORT StringLit NEWLINE
    ;

StructDecl
    = DEF TypeId NEWLINE INDENT {MemberDefinition} DEDENT   
    | DEF TypeId NEWLINE INDENT PASS NEWLINE DEDENT         
    | DEF TypeId '{' {GenericId} '}' NEWLINE INDENT {MemberIdTypeList} NEWLINE DEDENT 
    | DEF TypeId '{' {GenericId} '}' NEWLINE INDENT PASS NEWLINE DEDENT 
    ;

MemberDefinition 
    = MemberId TypeExpr 
    ;

FuncDecl
    = DEF NulliFuncDecl 
    | DEF MonoFuncDecl  
    | DEF BiFuncDecl    
    | DEF TriFuncDecl   
    ;

(* 0 Arg Func *)
NulliFuncDecl 
    = FuncId '->' TypeExpr Block 
    | FuncId Block 
    ;

(* 1 Arg Func *)
MonoFuncDecl 
    = Arg FuncId '->' TypeExpr Block 
    | Arg FuncId Block 
    ;

(* 2 Arg Func *)
BiFuncDecl
    = Arg FuncId Arg '->' TypeExpr Block 
    | Arg OpId Arg '->' TypeExpr Block
    ;

(* 3 or more Arg Func *)
TriFuncDecl
    = Arg FuncId '(' Arg {SubFuncId Arg}')' '->' TypeExpr Block
    ;

Block
    = NEWLINE INDENT {Stmt} DEDENT
    | NEWLINE INDENT JavascriptCodeSnippet NEWLINE DEDENT
    | NEWLINE INDENT PASS NEWLINE DEDENT
    ;

Stmt
    = AssignmentStmt
    | ReturnStmt   
    | AtomicFuncCall    NEWLINE
    | OpFuncCall  NEWLINE
    | IfStmt              
    | ForStmt
    | WhileStmt
    ;

ReturnStmt
    = RETURN MultilineExpr 
    ;

ForStmt
    = FOR VarId IN SinglelineExpr Block
    ;

WhileStmt
    = WHILE Test Block
    ;

IfStmt
    = IF Test Block [{ELIF Test Block}] [ELSE Block]
    ;

Test
    = SinglelineExpr                           
    | SinglelineExpr LogicOp Test        
    | NOT SinglelineExpr                   
    | NOT SinglelineExpr LogicOp Test
    ;

AssignmentStmt
    = LET VarDecl '=' MultilineExpr
    | VarId '=' MultilineExpr        
    ;

VarDecl 
    = VarId                          
    | VarId MUTABLE                  
    | VarId TypeExpr           
    | VarId TypeExpr MUTABLE   
    | '(' VarId ')'                  
    | '(' VarId TypeExpr ')'   
    ;

TypeExpr
    = AtomicTypeExpr '|' TypeExpr
    | AtomicTypeExpr '&' TypeExpr
    | AtomicTypeExpr 
    ;

AtomicTypeExpr
    = TypeId     
    | TypeId '?'
    | GenericAtom
    | GenericAtom '?'           
    | TypeId '{' {TypeExprList} '}'     
    | TypeId '{' {TypeExprList} '}' '?' 
    ;

MultilineExpr
    = MultilineObject
    | MulitilineDictionary
    | MultilineList
    | SinglelineExpr NEWLINE
    ;

SinglelineExpr
    = AtomicExpr
    | OpFuncCall
    ;

OpFuncCall
    = OpFuncCall OpId AtomicExpr {$$=_FuncCall("Bi",[$2],[$1,$3],this._$)}
    | AtomicExpr OpId AtomicExpr {$$=_FuncCall("Bi",[$2],[$1,$3],this._$)}
    ;

AtomicFuncCall
    = NulliFuncCall
    | MonoFuncCall
    | BiFuncCall
    | TriFuncCall
    ;

NulliFuncCall
    = FuncId  {$$=_FuncCall("Nulli",[$1],[],this._$)}
    ;

MonoFuncCall
    = AtomicExpr FuncId {$$=_FuncCall("Mono",[$2],[$1],this._$)}
    ;

BiFuncCall
    = AtomicExpr FuncId '(' SinglelineExpr ')'  
        {$$=_FuncCall("Bi",[$2],[$1,$4],this._$)}
    ;

TriFuncCall
    = AtomicExpr FuncId '(' SinglelineExpr VarId SinglelineExpr ')'  
        {$$=_FuncCall("Tri",[$2,$5],[$1,$4,$6],this._$)}
    ;

AtomicExpr 
    = '(' SinglelineExpr ')' 
    | ObjectAccessExpr
    | SinglelineList
    | AtomicFuncCall 
    | BooleanAtom
    | StringAtom
    | NumberAtom
    | EnumAtom {$$=_EnumExpr($1)}
    | VarId
    | AnonymousExpr
    | NIL
    ;

ObjectAccessExpr
    = AtomicExpr MemberId {$$=_ObjectAccess($1,$2)}
    ;

MultilineObject
    = TypeId NEWLINE {$$=_ObjectExpr($1,null)}
    | TypeId NEWLINE INDENT MultilineObjectKeyValueList DEDENT {$$=_ObjectExpr($1,$4)}
    ;

MultilineObjectKeyValueList
    = MultilineObjectKeyValue MultilineObjectKeyValueList {$$=_LinkedNode($1,$2)}
    | MultilineObjectKeyValue {$$=_LinkedNode($1,null)}
    ;

MultilineObjectKeyValue
    = MemberId ASSIGN_OP MultilineExpr {$$=_KeyValue($1,$3)}
    ;

MulitilineDictionary
    = '{' '}'
    | NEWLINE INDENT MultilineDictionaryKeyValueList DEDENT {$$=_ObjectExpr(null, $3)}
    ;

MultilineDictionaryKeyValueList
    = MultilineDictionaryKeyValue MultilineDictionaryKeyValueList {$$=_LinkedNode($1,$2)}
    | MultilineDictionaryKeyValue {$$=_LinkedNode($1,null)}
    ;

MultilineDictionaryKeyValue
    = StringAtom ASSIGN_OP MultilineExpr {$$=_KeyValue($1,$3)}
    ;

SinglelineObject
    = '{' KeyValueList '}' {$$=_ObjectExpr($2)}
    ;

KeyValueList
    = KeyValue KeyValueList {$$=_LinkedNode($1,$3)}
    | KeyValue                  {$$=_LinkedNode($1,null)}
    ;

KeyValue 
    = MemberId ASSIGN_OP SinglelineExpr   {$$=_KeyValue($1,$3)}
    | StringAtom ASSIGN_OP SinglelineExpr       {$$=_KeyValue($1,$3)}
    ;

SinglelineList
    = '[' Elements ']'   {$$=_ListExpr($2,this._$)}
    | '[' ']'            {$$=_ListExpr(null,this._$)}
    ;

Elements
    = AtomicExpr ',' Elements  {$$=_LinkedNode($1,$3)}
    | AtomicExpr {$$=_LinkedNode($1,null)}
    ;

MultilineList
    = NEWLINE INDENT MultilineElements DEDENT {$$=_ListExpr($3,this._$)}
    ;

MultilineElements
    = LIST_BULLET SinglelineExpr NEWLINE MultilineElements {$$=_LinkedNode($2,$4)}
    | LIST_BULLET SinglelineExpr NEWLINE {$$=_LinkedNode($2,null)}
    ;

BooleanAtom
    = TRUE  {$$=_BooleanExpr($1, this._$)}
    | FALSE {$$=_BooleanExpr($1, this._$)}
    ;

StringAtom
    = STRING {$$=_StringExpr($1, this._$)}
    ;

NumberAtom
    = NUMBER {$$=_NumberExpr($1, this._$)}
    ;

FuncId
    = FUNCNAME {$$=_Token($1, this._$)}
    ;

SubFuncId
    = SUBFUNCNAME {$$=_Token($1, this._$)}
    ;

MemberId
    = MemberId {$$=_Token($1, this._$)}
    ;

OpId    
    = Op {$$=_Token($1, this._$)}
    ;

TypeId
    = TYPENAME {$$=_Token($1, this._$)}
    ;

EnumAtom
    = ENUM {$$=_Token($1, this._$)}
    ;

GenericAtom
    = GENERICTYPENAME {$$=_Token($1, this._$)}
    ;

JavascriptCodeSnippet
    = JAVASCRIPT {$$=_JavascriptCode($1, this._$)}
    ;

LogicOp
    = AND {$$=_Token($1, this._$)}
    | OR  {$$=_Token($1, this._$)}
    ;

AnonymousExpr
    = '_' {$$=_AnonymousExpr(this._$)}
    ;