// def T IsComparable
//     def (this T) == (that T) -> Boolean
//         pass
    
//     def (this T) != (that T) -> Boolean
//         return (this == that).not
    
def Color
    :red    Integer
    :green  Integer
    :blue   Integer

// def (this List{T}).sort -> List{T} where T IsComparable
    

def (this Color) == (that Color) -> Boolean
    return  (this:red   == that:red)
        .and(this:green == that:green)
        .and(this:blue  == that:blue)

def ().main
    let colors mutable = List{Color}
    for i in 0..<2
        "Enter color $((i+1).toString)".show
        let color = Color
            :red   = "Enter red > ".ask.toInteger
            :green = "Enter green > ".ask.toInteger
            :blue  = "Enter blue > ".ask.toInteger
        colors = colors.append(color)
        
    if colors.(0) == colors.(1)
        "The two color are the same".show
    else
        "They are not same".show

    // let age = "How old are you?".ask.toInteger
    // if age > 50
    //     "You are old".show
    // else
    //     "You are young".show

    // if #false
    //     let str = "Enter a string > ".ask
    //     let old = "Which old char you want to replace > ".ask
    //     let new = "Replace with? > ".ask
    //     let result = str.replace(old with new)
    //     "The result is '$(result)'".show
    // else 
